# Generated by Django 3.1.7 on 2021-03-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_textresponse_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textresponse',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='textresponse',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='mainApp.person'),
        ),
    ]
