# Generated by Django 3.1.7 on 2021-04-02 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_question_nextquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='nextquestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
