# Generated by Django 3.2.3 on 2021-05-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_survey_remindertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='reminderTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
