# Generated by Django 3.2.3 on 2021-05-31 00:50

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_survey_remindertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='UTC', null=True),
        ),
    ]
