# Generated by Django 3.2.3 on 2021-05-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_survey_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='reminderTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
